name: Run tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main", "rfc*"]
  pull_request:
    branches: ["main", "rfc*"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      UV_NO_SYNC: "1"
    strategy:
      matrix:
        python-version: ["3.11"]
        with-zarr: [true, false]
        resolution: [highest, lowest-direct]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --no-dev --group test ${{ matrix.with-zarr && '--extra zarr' || '' }}
        env:
          UV_RESOLUTION: ${{ matrix.resolution }}

      - name: Run tests
        run: uv run pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
